config/routes.rb
Kohdr::Application.routes.draw do
    



  devise_for :user do
    get "logout" => "devise/sessions#destroy"
  end

  match "dashboard", :to => "authenticated#index"
  
  

  
  
  namespace :api do
    resources :headlines
    resources :pages
  end



  # the Admin                                                                   (http://www.domain.com/admin)
  # ---------------------------------------------------------------------------------------------------------
  
  namespace :admin do
  
    root :to => "users#index"
    
    resources :users do
      collection do
        get :admins
        get :deleted
      end
      member do
        get :delete
        get :undelete
      end
    end
      resources :headlines
      resources :pages
    
    
  end
  
end

app/views/admin/pages/_form.html.haml
= simple_form_for([:admin, @page], :defaults => { :input_html => { :class => 'input-xlarge' } }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :url
    = f.input :duration
    = f.input :login_script

  .form-actions
    = f.button :submit, :class => "btn-primary"

app/views/admin/pages/edit.html.haml
%section#content.container
  .page-header
    = link_to admin_pages_path, :class => 'btn' do
      %i.icon-list-alt
      Back
    = link_to [:admin, @page], :class => 'btn btn-primary' do
      %i.icon-info-sign.icon-white
      Show
    %h1 Editing page

  = render 'form'

app/views/admin/pages/index.html.haml
%section#content.container
  .page-header
    = link_to new_admin_page_path, :class => 'btn btn-primary' do
      %i.icon-plus.icon-white
      New Page
    %h1 Listing pages

  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th Url
        %th Duration
        %th
        %th
        %th

    %tbody
      - @pages.each do |page|
        %tr
          %td= page.url
          %td= page.duration
          %td= link_to 'Show', [:admin, page]
          %td= link_to 'Edit', edit_admin_page_path(page)
          %td= link_to 'Destroy', [:admin, page], :confirm => 'Are you sure?', :method => :delete

app/views/admin/pages/new.html.haml
%section#content.container
  .page-header
    = link_to admin_pages_path, :class => 'btn' do
      %i.icon-list-alt
      Back
    %h1 New page

  = render 'form'

app/views/admin/pages/show.html.haml
%section#content.container
  .page-header
    = link_to admin_pages_path, :class => 'btn' do
      %i.icon-list-alt
      Back
    = link_to edit_admin_page_path(@page), :class => 'btn btn-primary' do
      %i.icon-pencil.icon-white
      Edit
    %h1 Listing pages

  %dl
    %dt Url:
    %dd= @page.url
    %dt Duration:
    %dd= @page.duration