config/routes.rb
Kohdr::Application.routes.draw do
    



  devise_for :user do
    get "logout" => "devise/sessions#destroy"
  end

  match "dashboard", :to => "authenticated#index"
  
  

  
  
  namespace :api do
    resources :headlines
    resources :pages
  end



  # the Admin                                                                   (http://www.domain.com/admin)
  # ---------------------------------------------------------------------------------------------------------
  
  namespace :admin do
  
    root :to => "users#index"
    
    resources :users do
      collection do
        get :admins
        get :deleted
      end
      member do
        get :delete
        get :undelete
      end
    end
      resources :headlines
      resources :pages
    
    
  end
  
end

app/models/headline.rb
class Headline < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/admin/headlines_controller.rb
class Admin::HeadlinesController < Admin::AdminController
  # GET /headlines
  # GET /headlines.json
  def index
    @headlines = Headline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @headlines }
    end
  end

  # GET /headlines/1
  # GET /headlines/1.json
  def show
    @headline = Headline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @headline }
    end
  end

  # GET /headlines/new
  # GET /headlines/new.json
  def new
    @headline = Headline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @headline }
    end
  end

  # GET /headlines/1/edit
  def edit
    @headline = Headline.find(params[:id])
  end

  # POST /headlines
  # POST /headlines.json
  def create
    @headline = Headline.new(params[:headline])

    respond_to do |format|
      if @headline.save
        format.html { redirect_to [:admin, @headline], notice: 'Headline was successfully created.' }
        format.json { render json: @headline, status: :created, location: @headline }
      else
        format.html { render action: "new" }
        format.json { render json: @headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /headlines/1
  # PUT /headlines/1.json
  def update
    @headline = Headline.find(params[:id])

    respond_to do |format|
      if @headline.update_attributes(params[:headline])
        format.html { redirect_to [:admin, @headline], notice: 'Headline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headlines/1
  # DELETE /headlines/1.json
  def destroy
    @headline = Headline.find(params[:id])
    @headline.destroy

    respond_to do |format|
      format.html { redirect_to admin_headlines_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/api/headlines_controller.rb
class Api::HeadlinesController < ActionController::Base
  def index
    @headlines = Headline.all
    render :json => {headlines: @headlines}
  end
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
end

app/views/admin/headlines/_form.html.haml
= simple_form_for([:admin, @headline], :defaults => { :input_html => { :class => 'input-xlarge' } }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :body

  .form-actions
    = f.button :submit, :class => "btn-primary"

app/views/admin/headlines/edit.html.haml
%section#content.container
  .page-header
    = link_to admin_headlines_path, :class => 'btn' do
      %i.icon-list-alt
      Back
    = link_to [:admin, @headline], :class => 'btn btn-primary' do
      %i.icon-info-sign.icon-white
      Show
    %h1 Editing headline

  = render 'form'

app/views/admin/headlines/index.html.haml
%section#content.container
  .page-header
    = link_to new_admin_headline_path, :class => 'btn btn-primary' do
      %i.icon-plus.icon-white
      New Headline
    %h1 Listing headlines

  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th Title
        %th Body
        %th
        %th
        %th

    %tbody
      - @headlines.each do |headline|
        %tr
          %td= headline.title
          %td= headline.body
          %td= link_to 'Show', [:admin, headline]
          %td= link_to 'Edit', edit_admin_headline_path(headline)
          %td= link_to 'Destroy', [:admin, headline], :confirm => 'Are you sure?', :method => :delete

app/views/admin/headlines/new.html.haml
%section#content.container
  .page-header
    = link_to admin_headlines_path, :class => 'btn' do
      %i.icon-list-alt
      Back
    %h1 New headline

  = render 'form'

app/views/admin/headlines/show.html.haml
%section#content.container
  .page-header
    = link_to admin_headlines_path, :class => 'btn' do
      %i.icon-list-alt
      Back
    = link_to edit_admin_headline_path(@headline), :class => 'btn btn-primary' do
      %i.icon-pencil.icon-white
      Edit
    %h1 Listing headlines

  %dl
    %dt Title:
    %dd= @headline.title
    %dt Body:
    %dd= @headline.body